// <auto-generated />
using System;
using CoffeeShopAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShopAPI.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    [Migration("20250203194440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("CoffeeShopAPI.Models.CoffeeShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("coffee_shops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            Location = "New York, NY",
                            Name = "Central Perk",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 2,
                            ClosingTime = new TimeSpan(0, 21, 0, 0, 0),
                            Location = "San Francisco, CA",
                            Name = "Java House",
                            OpeningTime = new TimeSpan(0, 15, 30, 0, 0),
                            Rating = 4.0m
                        },
                        new
                        {
                            Id = 3,
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Location = "Los Angeles, CA",
                            Name = "The Coffee Bean",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            Rating = 4.7m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
